package com.nalu.umbrella.repository.model;

import java.io.Serializable;
import java.util.Date;

public class UmbrellaPicture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.UMBRELLA_ADDRESS
     *
     * @mbg.generated
     */
    private String umbrellaAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.ADDRESS_NAME
     *
     * @mbg.generated
     */
    private String addressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.PICTURE_URL
     *
     * @mbg.generated
     */
    private String pictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.ISDELETED
     *
     * @mbg.generated
     */
    private Integer isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.CREATED_DATE
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.CITY_REMARK
     *
     * @mbg.generated
     */
    private String cityRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column umbrella_picture.PICTURE_SMALL_URL
     *
     * @mbg.generated
     */
    private String pictureSmallUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.ID
     *
     * @return the value of umbrella_picture.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.ID
     *
     * @param id the value for umbrella_picture.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.UMBRELLA_ADDRESS
     *
     * @return the value of umbrella_picture.UMBRELLA_ADDRESS
     *
     * @mbg.generated
     */
    public String getUmbrellaAddress() {
        return umbrellaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.UMBRELLA_ADDRESS
     *
     * @param umbrellaAddress the value for umbrella_picture.UMBRELLA_ADDRESS
     *
     * @mbg.generated
     */
    public void setUmbrellaAddress(String umbrellaAddress) {
        this.umbrellaAddress = umbrellaAddress == null ? null : umbrellaAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.ADDRESS_NAME
     *
     * @return the value of umbrella_picture.ADDRESS_NAME
     *
     * @mbg.generated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.ADDRESS_NAME
     *
     * @param addressName the value for umbrella_picture.ADDRESS_NAME
     *
     * @mbg.generated
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.PICTURE_URL
     *
     * @return the value of umbrella_picture.PICTURE_URL
     *
     * @mbg.generated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.PICTURE_URL
     *
     * @param pictureUrl the value for umbrella_picture.PICTURE_URL
     *
     * @mbg.generated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.ISDELETED
     *
     * @return the value of umbrella_picture.ISDELETED
     *
     * @mbg.generated
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.ISDELETED
     *
     * @param isdeleted the value for umbrella_picture.ISDELETED
     *
     * @mbg.generated
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.CREATED_DATE
     *
     * @return the value of umbrella_picture.CREATED_DATE
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.CREATED_DATE
     *
     * @param createdDate the value for umbrella_picture.CREATED_DATE
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.UPDATE_DATE
     *
     * @return the value of umbrella_picture.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.UPDATE_DATE
     *
     * @param updateDate the value for umbrella_picture.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.CITY_REMARK
     *
     * @return the value of umbrella_picture.CITY_REMARK
     *
     * @mbg.generated
     */
    public String getCityRemark() {
        return cityRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.CITY_REMARK
     *
     * @param cityRemark the value for umbrella_picture.CITY_REMARK
     *
     * @mbg.generated
     */
    public void setCityRemark(String cityRemark) {
        this.cityRemark = cityRemark == null ? null : cityRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umbrella_picture.PICTURE_SMALL_URL
     *
     * @return the value of umbrella_picture.PICTURE_SMALL_URL
     *
     * @mbg.generated
     */
    public String getPictureSmallUrl() {
        return pictureSmallUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umbrella_picture.PICTURE_SMALL_URL
     *
     * @param pictureSmallUrl the value for umbrella_picture.PICTURE_SMALL_URL
     *
     * @mbg.generated
     */
    public void setPictureSmallUrl(String pictureSmallUrl) {
        this.pictureSmallUrl = pictureSmallUrl == null ? null : pictureSmallUrl.trim();
    }
}