package com.nalu.umbrella.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UmbrellaPictureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public UmbrellaPictureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressIsNull() {
            addCriterion("UMBRELLA_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressIsNotNull() {
            addCriterion("UMBRELLA_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressEqualTo(String value) {
            addCriterion("UMBRELLA_ADDRESS =", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressNotEqualTo(String value) {
            addCriterion("UMBRELLA_ADDRESS <>", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressGreaterThan(String value) {
            addCriterion("UMBRELLA_ADDRESS >", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressGreaterThanOrEqualTo(String value) {
            addCriterion("UMBRELLA_ADDRESS >=", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressLessThan(String value) {
            addCriterion("UMBRELLA_ADDRESS <", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressLessThanOrEqualTo(String value) {
            addCriterion("UMBRELLA_ADDRESS <=", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressLike(String value) {
            addCriterion("UMBRELLA_ADDRESS like", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressNotLike(String value) {
            addCriterion("UMBRELLA_ADDRESS not like", value, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressIn(List<String> values) {
            addCriterion("UMBRELLA_ADDRESS in", values, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressNotIn(List<String> values) {
            addCriterion("UMBRELLA_ADDRESS not in", values, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressBetween(String value1, String value2) {
            addCriterion("UMBRELLA_ADDRESS between", value1, value2, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andUmbrellaAddressNotBetween(String value1, String value2) {
            addCriterion("UMBRELLA_ADDRESS not between", value1, value2, "umbrellaAddress");
            return (Criteria) this;
        }

        public Criteria andAddressNameIsNull() {
            addCriterion("ADDRESS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAddressNameIsNotNull() {
            addCriterion("ADDRESS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAddressNameEqualTo(String value) {
            addCriterion("ADDRESS_NAME =", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotEqualTo(String value) {
            addCriterion("ADDRESS_NAME <>", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameGreaterThan(String value) {
            addCriterion("ADDRESS_NAME >", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS_NAME >=", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameLessThan(String value) {
            addCriterion("ADDRESS_NAME <", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS_NAME <=", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameLike(String value) {
            addCriterion("ADDRESS_NAME like", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotLike(String value) {
            addCriterion("ADDRESS_NAME not like", value, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameIn(List<String> values) {
            addCriterion("ADDRESS_NAME in", values, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotIn(List<String> values) {
            addCriterion("ADDRESS_NAME not in", values, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameBetween(String value1, String value2) {
            addCriterion("ADDRESS_NAME between", value1, value2, "addressName");
            return (Criteria) this;
        }

        public Criteria andAddressNameNotBetween(String value1, String value2) {
            addCriterion("ADDRESS_NAME not between", value1, value2, "addressName");
            return (Criteria) this;
        }

        public Criteria andPictureUrlIsNull() {
            addCriterion("PICTURE_URL is null");
            return (Criteria) this;
        }

        public Criteria andPictureUrlIsNotNull() {
            addCriterion("PICTURE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPictureUrlEqualTo(String value) {
            addCriterion("PICTURE_URL =", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotEqualTo(String value) {
            addCriterion("PICTURE_URL <>", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlGreaterThan(String value) {
            addCriterion("PICTURE_URL >", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PICTURE_URL >=", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlLessThan(String value) {
            addCriterion("PICTURE_URL <", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlLessThanOrEqualTo(String value) {
            addCriterion("PICTURE_URL <=", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlLike(String value) {
            addCriterion("PICTURE_URL like", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotLike(String value) {
            addCriterion("PICTURE_URL not like", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlIn(List<String> values) {
            addCriterion("PICTURE_URL in", values, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotIn(List<String> values) {
            addCriterion("PICTURE_URL not in", values, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlBetween(String value1, String value2) {
            addCriterion("PICTURE_URL between", value1, value2, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotBetween(String value1, String value2) {
            addCriterion("PICTURE_URL not between", value1, value2, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("ISDELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("ISDELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(Integer value) {
            addCriterion("ISDELETED =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(Integer value) {
            addCriterion("ISDELETED <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(Integer value) {
            addCriterion("ISDELETED >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("ISDELETED >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(Integer value) {
            addCriterion("ISDELETED <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(Integer value) {
            addCriterion("ISDELETED <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<Integer> values) {
            addCriterion("ISDELETED in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<Integer> values) {
            addCriterion("ISDELETED not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(Integer value1, Integer value2) {
            addCriterion("ISDELETED between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("ISDELETED not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCityRemarkIsNull() {
            addCriterion("CITY_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andCityRemarkIsNotNull() {
            addCriterion("CITY_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andCityRemarkEqualTo(String value) {
            addCriterion("CITY_REMARK =", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkNotEqualTo(String value) {
            addCriterion("CITY_REMARK <>", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkGreaterThan(String value) {
            addCriterion("CITY_REMARK >", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_REMARK >=", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkLessThan(String value) {
            addCriterion("CITY_REMARK <", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkLessThanOrEqualTo(String value) {
            addCriterion("CITY_REMARK <=", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkLike(String value) {
            addCriterion("CITY_REMARK like", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkNotLike(String value) {
            addCriterion("CITY_REMARK not like", value, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkIn(List<String> values) {
            addCriterion("CITY_REMARK in", values, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkNotIn(List<String> values) {
            addCriterion("CITY_REMARK not in", values, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkBetween(String value1, String value2) {
            addCriterion("CITY_REMARK between", value1, value2, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andCityRemarkNotBetween(String value1, String value2) {
            addCriterion("CITY_REMARK not between", value1, value2, "cityRemark");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlIsNull() {
            addCriterion("PICTURE_SMALL_URL is null");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlIsNotNull() {
            addCriterion("PICTURE_SMALL_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlEqualTo(String value) {
            addCriterion("PICTURE_SMALL_URL =", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlNotEqualTo(String value) {
            addCriterion("PICTURE_SMALL_URL <>", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlGreaterThan(String value) {
            addCriterion("PICTURE_SMALL_URL >", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PICTURE_SMALL_URL >=", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlLessThan(String value) {
            addCriterion("PICTURE_SMALL_URL <", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlLessThanOrEqualTo(String value) {
            addCriterion("PICTURE_SMALL_URL <=", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlLike(String value) {
            addCriterion("PICTURE_SMALL_URL like", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlNotLike(String value) {
            addCriterion("PICTURE_SMALL_URL not like", value, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlIn(List<String> values) {
            addCriterion("PICTURE_SMALL_URL in", values, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlNotIn(List<String> values) {
            addCriterion("PICTURE_SMALL_URL not in", values, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlBetween(String value1, String value2) {
            addCriterion("PICTURE_SMALL_URL between", value1, value2, "pictureSmallUrl");
            return (Criteria) this;
        }

        public Criteria andPictureSmallUrlNotBetween(String value1, String value2) {
            addCriterion("PICTURE_SMALL_URL not between", value1, value2, "pictureSmallUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umbrella_picture
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}