package com.nalu.umbrella.repository.model;

import java.io.Serializable;
import java.util.Date;

public class WeixinUserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.NICK_NAME
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.AVATAR_URL
     *
     * @mbg.generated
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.OPEN_ID
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.ISDELETED
     *
     * @mbg.generated
     */
    private Integer isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.CREATED_DATE
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_info.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.ID
     *
     * @return the value of weixin_user_info.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.ID
     *
     * @param id the value for weixin_user_info.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.NICK_NAME
     *
     * @return the value of weixin_user_info.NICK_NAME
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.NICK_NAME
     *
     * @param nickName the value for weixin_user_info.NICK_NAME
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.AVATAR_URL
     *
     * @return the value of weixin_user_info.AVATAR_URL
     *
     * @mbg.generated
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.AVATAR_URL
     *
     * @param avatarUrl the value for weixin_user_info.AVATAR_URL
     *
     * @mbg.generated
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.OPEN_ID
     *
     * @return the value of weixin_user_info.OPEN_ID
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.OPEN_ID
     *
     * @param openId the value for weixin_user_info.OPEN_ID
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.ISDELETED
     *
     * @return the value of weixin_user_info.ISDELETED
     *
     * @mbg.generated
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.ISDELETED
     *
     * @param isdeleted the value for weixin_user_info.ISDELETED
     *
     * @mbg.generated
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.CREATED_DATE
     *
     * @return the value of weixin_user_info.CREATED_DATE
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.CREATED_DATE
     *
     * @param createdDate the value for weixin_user_info.CREATED_DATE
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_info.UPDATE_DATE
     *
     * @return the value of weixin_user_info.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_info.UPDATE_DATE
     *
     * @param updateDate the value for weixin_user_info.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}