package com.nalu.umbrella.repository.model;

import java.io.Serializable;
import java.util.Date;

public class WeixinJoinRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.OPEN_ID
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.CITY_CODE
     *
     * @mbg.generated
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.RECORD_ID
     *
     * @mbg.generated
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.ISDELETED
     *
     * @mbg.generated
     */
    private Integer isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.CREATED_DATE
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_join_record.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.ID
     *
     * @return the value of weixin_join_record.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.ID
     *
     * @param id the value for weixin_join_record.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.OPEN_ID
     *
     * @return the value of weixin_join_record.OPEN_ID
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.OPEN_ID
     *
     * @param openId the value for weixin_join_record.OPEN_ID
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.CITY_CODE
     *
     * @return the value of weixin_join_record.CITY_CODE
     *
     * @mbg.generated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.CITY_CODE
     *
     * @param cityCode the value for weixin_join_record.CITY_CODE
     *
     * @mbg.generated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.RECORD_ID
     *
     * @return the value of weixin_join_record.RECORD_ID
     *
     * @mbg.generated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.RECORD_ID
     *
     * @param recordId the value for weixin_join_record.RECORD_ID
     *
     * @mbg.generated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.ISDELETED
     *
     * @return the value of weixin_join_record.ISDELETED
     *
     * @mbg.generated
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.ISDELETED
     *
     * @param isdeleted the value for weixin_join_record.ISDELETED
     *
     * @mbg.generated
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.CREATED_DATE
     *
     * @return the value of weixin_join_record.CREATED_DATE
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.CREATED_DATE
     *
     * @param createdDate the value for weixin_join_record.CREATED_DATE
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_join_record.UPDATE_DATE
     *
     * @return the value of weixin_join_record.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_join_record.UPDATE_DATE
     *
     * @param updateDate the value for weixin_join_record.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}