package com.nalu.umbrella.repository.mapper;

import com.nalu.umbrella.repository.model.UmbrellaPicture;
import com.nalu.umbrella.repository.model.UmbrellaPictureExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UmbrellaPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    long countByExample(UmbrellaPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    int insert(UmbrellaPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    int insertSelective(UmbrellaPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    List<UmbrellaPicture> selectByExample(UmbrellaPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    UmbrellaPicture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UmbrellaPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umbrella_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UmbrellaPicture record);
}