package com.nalu.umbrella.repository.mapper;

import com.nalu.umbrella.repository.model.WeixinJoinRecord;
import com.nalu.umbrella.repository.model.WeixinJoinRecordExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface WeixinJoinRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    long countByExample(WeixinJoinRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    int insert(WeixinJoinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    int insertSelective(WeixinJoinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    List<WeixinJoinRecord> selectByExample(WeixinJoinRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    WeixinJoinRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeixinJoinRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_join_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeixinJoinRecord record);
}