package com.nalu.umbrella.repository.mapper;

import com.nalu.umbrella.repository.model.WeixinUserInfo;
import com.nalu.umbrella.repository.model.WeixinUserInfoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface WeixinUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    long countByExample(WeixinUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    int insert(WeixinUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    int insertSelective(WeixinUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    List<WeixinUserInfo> selectByExample(WeixinUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    WeixinUserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeixinUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeixinUserInfo record);
}